### PR TITLE
Minor code cleanup

### PR DESCRIPTION
**Pull request by spaikmos**
- expand import statements
- remove unused local variables
- remove extraneous parens
- cleanup comments

### CODE REVIEW

**Comment by spaikmos** [comment]
As I was preparing to pull the recent changes into our repo, I found minor code edits made in our local repository, likely by an auto-formatter.  I thought this might be useful to upstream.

**Comment by makinako** [comment]
Hi I'll just have to be a bit careful with how I merge this as I've got a lot of general code review and cleanup changes in the [ecc-review-changes](https://github.com/makinako/OpenFIPS201/tree/feature/ecc-review-changes) branch that I'll be merging shortly. 
There is a bit of overlap here so I will probably selectively merge this PR into the ECC branch in first so I can run all tests.

**Comment by spaikmos** [comment]
ah!  I didn't realize you have another change in flight.  Do you know when your ecc-review-changes will go in?  I can create a CL off of that branch that incorporates these changes, or wait until after you merge and submit then.  Either way is fine.

**Comment by makinako** [comment]
> ah! I didn't realize you have another change in flight. Do you know when your ecc-review-changes will go in? I can create a CL off of that branch that incorporates these changes, or wait until after you merge and submit then. Either way is fine.

I am aiming to merge at the end of the week, so I'm happy for us to cancel this one and you can run it against the branch before we do. I'd like to do a final run of all the testing on our target cards before the merge so it's better to get in as much as possible.

**Comment by makinako** [comment]
@spaikmos I have merged all changes from ecc-review-changes, so it's good to go if you want to re-run your automated checks.

**Comment by spaikmos** [comment]
Thanks!  It looks like you got most of my proposed changes, so I'll create a new PR with the rest.

**Pull request closed without merging**
